### ISSUE TITLE
Hot reloading doesn't work

### ISSUE THREAD

**Issue by ftoh** [netlify/live-tunnel-client#6]
**To reproduce**
1. edit _netlify.toml_
```toml
[dev]
command = "npx parcel index.html"
publish = "dist"
```
2. run command 
```bash
$ netlify dev --live
```
3. edit file index.html

**Expected behavior**
Page reloads after receiving command via WebSocket after file edits

**Actual behavior**
Nothing happens
